export const theme = {
  colors: {
    background: '#080d1a',
    backgroundSecondary: '#0d1526',
    backgroundTertiary: '#111d35',
    accentPrimary: '#7B5EA7',
    accentSecondary: '#5B8DEF',
    accentGradientStart: '#7B5EA7',
    accentGradientEnd: '#5B8DEF',
    textPrimary: '#FFFFFF',
    textSecondary: '#8899AA',
    textMuted: '#4A5568',
    border: '#1a2540',
    borderLight: '#1e2d4a',
    success: '#48BB78',
    error: '#FC8181',
    warning: '#F6AD55',
  },
  fonts: {
    regular: 'System',
    medium: 'System',
    bold: 'System',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
};